# Generated by Django 5.0 on 2024-02-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
